# Generated by Django 6.0.4 on 2026-04-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя ученика')),
                ('number_of_class', models.IntegerField(choices=[(1, '1-й класс'), (2, '2-й класс'), (3, '3-й класс'), (4, '4-й класс'), (5, '5-й класс'), (6, '6-й класс'), (7, '7-й класс'), (8, '8-й класс'), (9, '9-й класс'), (10, '10-й класс'), (11, '11-й класс')], verbose_name='Класс ученика')),
            ],
        ),
    ]
