# Generated by Django 6.0.4 on 2026-05-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_subscription_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='planned_lessons',
            field=models.IntegerField(default=0),
        ),
    ]
