# Generated by Django 6.0.4 on 2026-04-29 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_cancelledlesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_date', models.DateField()),
                ('new_date', models.DateField()),
                ('new_time_start', models.DateTimeField(blank=True, null=True)),
                ('new_time_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson')),
            ],
            options={
                'unique_together': {('lesson', 'old_date')},
            },
        ),
    ]
