# Generated by Django 6.0.4 on 2026-05-28 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lessonlog'),
        ('students', '0003_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancelled_lessons', to='lessons.lesson'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='students.student', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='transferredlesson',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfered_lessons', to='lessons.lesson'),
        ),
    ]
